apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dessert-ad-studio
resources:
  - namespace.yaml
  - app-config.yaml
  - outputs-pvc.yaml
  - triton-models-pvc.yaml
  - triton-deployment.yaml
  - api-deployment.yaml
  - app-deployment.yaml
  - ingress.yaml
