from __future__ import annotations

from dataclasses import dataclass

from dessert_ad_studio.schemas import CampaignPurpose, TemplateHint, Tone


@dataclass(frozen=True)
class DemoSample:
    label: str
    business_type: str
    platform: str
    product_name: str
    campaign_purpose: CampaignPurpose
    tone: Tone
    template_hint: TemplateHint
    price_text: str
    user_constraints: str


DEMO_SAMPLES: tuple[DemoSample, ...] = (
    DemoSample(
        label="디저트 카페 - 딸기 크림 크루아상",
        business_type="디저트 카페",
        platform="인스타그램 피드",
        product_name="딸기 크림 크루아상",
        campaign_purpose="new_menu",
        tone="warm",
        template_hint="cozy_cafe",
        price_text="6,800원",
        user_constraints="봄 시즌 한정 느낌, 따뜻한 카페 조명, 20대 여성 타깃",
    ),
    DemoSample(
        label="베이커리 - 말차 푸딩",
        business_type="베이커리",
        platform="인스타그램 스토리",
        product_name="말차 푸딩",
        campaign_purpose="seasonal_event",
        tone="premium",
        template_hint="minimal_premium",
        price_text="2개 세트 9,900원",
        user_constraints="진한 말차 풍미, 차분한 프리미엄 분위기, 시즌 한정 디저트",
    ),
    DemoSample(
        label="꽃집 - 플라워 박스",
        business_type="꽃집",
        platform="네이버 스마트스토어 썸네일",
        product_name="봄 플라워 박스",
        campaign_purpose="discount",
        tone="playful",
        template_hint="seasonal_event",
        price_text="예약 주문 10% 할인",
        user_constraints="선물용 추천, 화사한 봄 컬러, 주말 예약 주문 유도",
    ),
)


PRODUCT_LIKE_EVAL_SAMPLES: tuple[DemoSample, ...] = (
    DemoSample(
        label="카페 신메뉴 - 흑임자 크림 라떼",
        business_type="카페",
        platform="인스타그램 피드",
        product_name="흑임자 크림 라떼",
        campaign_purpose="new_menu",
        tone="premium",
        template_hint="minimal_premium",
        price_text="6,300원",
        user_constraints="고소한 크림, 오후 디저트 페어링, 차분한 프리미엄 톤",
    ),
    DemoSample(
        label="디저트 카페 - 바닐라빈 까눌레",
        business_type="디저트 카페",
        platform="인스타그램 스토리",
        product_name="바닐라빈 까눌레",
        campaign_purpose="new_menu",
        tone="warm",
        template_hint="cozy_cafe",
        price_text="3개 세트 8,500원",
        user_constraints="겉바속촉 식감, 선물용 패키지, 따뜻한 조명",
    ),
    DemoSample(
        label="베이커리 - 소금 버터롤",
        business_type="베이커리",
        platform="네이버 스마트스토어",
        product_name="소금 버터롤",
        campaign_purpose="seasonal_event",
        tone="clean",
        template_hint="cozy_cafe",
        price_text="4개입 7,200원",
        user_constraints="아침 식사 추천, 담백한 버터 풍미, 과장 표현 금지",
    ),
    DemoSample(
        label="브런치 카페 - 아보카도 에그 토스트",
        business_type="브런치 카페",
        platform="인스타그램 피드",
        product_name="아보카도 에그 토스트",
        campaign_purpose="new_menu",
        tone="clean",
        template_hint="minimal_premium",
        price_text="9,800원",
        user_constraints="신선한 재료, 점심 브런치 수요, 건강 효능 과장 금지",
    ),
    DemoSample(
        label="케이크샵 - 얼그레이 쉬폰 케이크",
        business_type="케이크샵",
        platform="인스타그램 릴스 커버",
        product_name="얼그레이 쉬폰 케이크",
        campaign_purpose="seasonal_event",
        tone="premium",
        template_hint="minimal_premium",
        price_text="조각 7,500원",
        user_constraints="은은한 홍차 향, 예약 주문 유도, 고급스러운 무드",
    ),
    DemoSample(
        label="마카롱샵 - 제주 말차 마카롱",
        business_type="마카롱샵",
        platform="카카오채널",
        product_name="제주 말차 마카롱",
        campaign_purpose="discount",
        tone="playful",
        template_hint="seasonal_event",
        price_text="6구 박스 15% 할인",
        user_constraints="선물 수요, 한정 할인, 원산지 표현은 사실 기반",
    ),
    DemoSample(
        label="빙수 카페 - 애플망고 빙수",
        business_type="빙수 카페",
        platform="인스타그램 피드",
        product_name="애플망고 빙수",
        campaign_purpose="seasonal_event",
        tone="playful",
        template_hint="seasonal_event",
        price_text="18,000원",
        user_constraints="여름 시즌, 시원한 색감, 무리한 건강 효능 표현 금지",
    ),
    DemoSample(
        label="도넛샵 - 라즈베리 글레이즈 도넛",
        business_type="도넛샵",
        platform="배달앱 배너",
        product_name="라즈베리 글레이즈 도넛",
        campaign_purpose="new_menu",
        tone="playful",
        template_hint="seasonal_event",
        price_text="3,900원",
        user_constraints="상큼한 컬러, 배달 주문 유도, 짧은 CTA",
    ),
    DemoSample(
        label="젤라또샵 - 피스타치오 젤라또",
        business_type="젤라또샵",
        platform="인스타그램 스토리",
        product_name="피스타치오 젤라또",
        campaign_purpose="new_menu",
        tone="premium",
        template_hint="minimal_premium",
        price_text="컵 5,800원",
        user_constraints="진한 견과 풍미, 이탈리안 무드, 차분한 색감",
    ),
    DemoSample(
        label="티하우스 - 복숭아 우롱 티",
        business_type="티하우스",
        platform="네이버 플레이스 소식",
        product_name="복숭아 우롱 티",
        campaign_purpose="seasonal_event",
        tone="warm",
        template_hint="cozy_cafe",
        price_text="6,000원",
        user_constraints="은은한 과일 향, 여름 오후 추천, 치료 효능 금지",
    ),
    DemoSample(
        label="쿠키샵 - 르뱅 초코칩 쿠키",
        business_type="쿠키샵",
        platform="인스타그램 피드",
        product_name="르뱅 초코칩 쿠키",
        campaign_purpose="new_menu",
        tone="warm",
        template_hint="cozy_cafe",
        price_text="4,500원",
        user_constraints="두툼한 식감, 커피 페어링, 따뜻한 베이커리 톤",
    ),
    DemoSample(
        label="타르트샵 - 레몬 머랭 타르트",
        business_type="타르트샵",
        platform="인스타그램 릴스 커버",
        product_name="레몬 머랭 타르트",
        campaign_purpose="new_menu",
        tone="clean",
        template_hint="minimal_premium",
        price_text="6,900원",
        user_constraints="상큼한 첫인상, 산뜻한 배경, 과장된 최상급 표현 자제",
    ),
    DemoSample(
        label="샌드위치 카페 - 바질 치킨 샌드위치",
        business_type="샌드위치 카페",
        platform="배달앱 배너",
        product_name="바질 치킨 샌드위치",
        campaign_purpose="discount",
        tone="clean",
        template_hint="minimal_premium",
        price_text="런치 세트 1,000원 할인",
        user_constraints="점심 주문, 신선한 재료, 빠른 CTA",
    ),
    DemoSample(
        label="수제청 카페 - 자몽 허니 에이드",
        business_type="수제청 카페",
        platform="인스타그램 스토리",
        product_name="자몽 허니 에이드",
        campaign_purpose="seasonal_event",
        tone="playful",
        template_hint="seasonal_event",
        price_text="5,900원",
        user_constraints="수제청 강조, 청량감, 건강 효능 과장 금지",
    ),
    DemoSample(
        label="크로플 카페 - 브라운치즈 크로플",
        business_type="크로플 카페",
        platform="인스타그램 피드",
        product_name="브라운치즈 크로플",
        campaign_purpose="new_menu",
        tone="warm",
        template_hint="cozy_cafe",
        price_text="8,500원",
        user_constraints="치즈 비주얼, 주말 디저트, 포근한 카페 톤",
    ),
    DemoSample(
        label="파운드케이크샵 - 유자 파운드케이크",
        business_type="파운드케이크샵",
        platform="네이버 스마트스토어",
        product_name="유자 파운드케이크",
        campaign_purpose="seasonal_event",
        tone="premium",
        template_hint="minimal_premium",
        price_text="한 박스 16,000원",
        user_constraints="선물 포장, 은은한 유자 향, 차분한 프리미엄 톤",
    ),
    DemoSample(
        label="푸딩샵 - 카라멜 커스터드 푸딩",
        business_type="푸딩샵",
        platform="인스타그램 피드",
        product_name="카라멜 커스터드 푸딩",
        campaign_purpose="new_menu",
        tone="warm",
        template_hint="cozy_cafe",
        price_text="4,800원",
        user_constraints="부드러운 식감, 디저트 타임, 따뜻한 색감",
    ),
    DemoSample(
        label="스콘샵 - 무화과 크림치즈 스콘",
        business_type="스콘샵",
        platform="인스타그램 스토리",
        product_name="무화과 크림치즈 스콘",
        campaign_purpose="seasonal_event",
        tone="premium",
        template_hint="minimal_premium",
        price_text="5,200원",
        user_constraints="가을 시즌, 크림치즈 풍미, 예약 주문 유도",
    ),
    DemoSample(
        label="컵케이크샵 - 블루베리 컵케이크",
        business_type="컵케이크샵",
        platform="카카오채널",
        product_name="블루베리 컵케이크",
        campaign_purpose="discount",
        tone="playful",
        template_hint="seasonal_event",
        price_text="4구 세트 12,000원",
        user_constraints="파티 간식, 선명한 컬러, 할인 CTA",
    ),
    DemoSample(
        label="로스터리 카페 - 콜드브루 라떼",
        business_type="로스터리 카페",
        platform="네이버 플레이스 소식",
        product_name="콜드브루 라떼",
        campaign_purpose="new_menu",
        tone="clean",
        template_hint="minimal_premium",
        price_text="5,500원",
        user_constraints="원두 향미, 출근길 수요, 과도한 각성 효능 표현 금지",
    ),
    DemoSample(
        label="한식 디저트 카페 - 흑임자 인절미 케이크",
        business_type="한식 디저트 카페",
        platform="인스타그램 피드",
        product_name="흑임자 인절미 케이크",
        campaign_purpose="new_menu",
        tone="premium",
        template_hint="minimal_premium",
        price_text="조각 7,200원",
        user_constraints="고소한 맛, 전통 디저트 재해석, 고급스러운 톤",
    ),
    DemoSample(
        label="요거트샵 - 그래놀라 그릭요거트",
        business_type="요거트샵",
        platform="배달앱 배너",
        product_name="그래놀라 그릭요거트",
        campaign_purpose="discount",
        tone="clean",
        template_hint="minimal_premium",
        price_text="아침 세트 10% 할인",
        user_constraints="아침 식사, 식감 강조, 다이어트 효능 과장 금지",
    ),
    DemoSample(
        label="초콜릿샵 - 다크 초콜릿 봉봉",
        business_type="초콜릿샵",
        platform="네이버 스마트스토어",
        product_name="다크 초콜릿 봉봉",
        campaign_purpose="seasonal_event",
        tone="premium",
        template_hint="minimal_premium",
        price_text="9구 박스 24,000원",
        user_constraints="선물용, 고급 패키지, 진한 카카오 풍미",
    ),
    DemoSample(
        label="와플샵 - 누텔라 바나나 와플",
        business_type="와플샵",
        platform="인스타그램 스토리",
        product_name="누텔라 바나나 와플",
        campaign_purpose="new_menu",
        tone="playful",
        template_hint="seasonal_event",
        price_text="7,900원",
        user_constraints="달콤한 비주얼, 친구와 공유, 밝은 톤",
    ),
    DemoSample(
        label="샐러드 카페 - 리코타 베리 샐러드",
        business_type="샐러드 카페",
        platform="배달앱 배너",
        product_name="리코타 베리 샐러드",
        campaign_purpose="new_menu",
        tone="clean",
        template_hint="minimal_premium",
        price_text="10,500원",
        user_constraints="신선한 베리, 가벼운 점심, 건강 효능 과장 금지",
    ),
    DemoSample(
        label="팬케이크 카페 - 메이플 수플레 팬케이크",
        business_type="팬케이크 카페",
        platform="인스타그램 피드",
        product_name="메이플 수플레 팬케이크",
        campaign_purpose="seasonal_event",
        tone="warm",
        template_hint="cozy_cafe",
        price_text="12,000원",
        user_constraints="폭신한 식감, 주말 브런치, 따뜻한 무드",
    ),
    DemoSample(
        label="프레첼샵 - 갈릭 크림치즈 프레첼",
        business_type="프레첼샵",
        platform="인스타그램 릴스 커버",
        product_name="갈릭 크림치즈 프레첼",
        campaign_purpose="new_menu",
        tone="clean",
        template_hint="cozy_cafe",
        price_text="4,900원",
        user_constraints="짭짤한 간식, 테이크아웃 유도, 짧은 메시지",
    ),
    DemoSample(
        label="허니브레드 카페 - 시나몬 허니브레드",
        business_type="허니브레드 카페",
        platform="카카오채널",
        product_name="시나몬 허니브레드",
        campaign_purpose="discount",
        tone="warm",
        template_hint="cozy_cafe",
        price_text="음료 세트 1,500원 할인",
        user_constraints="커플 방문, 달콤한 향, 세트 할인 강조",
    ),
    DemoSample(
        label="비건 베이커리 - 비건 초코 머핀",
        business_type="비건 베이커리",
        platform="네이버 스마트스토어",
        product_name="비건 초코 머핀",
        campaign_purpose="new_menu",
        tone="clean",
        template_hint="minimal_premium",
        price_text="3개입 9,000원",
        user_constraints="비건 재료, 담백한 단맛, 건강 효능 과장 금지",
    ),
    DemoSample(
        label="디저트 박스샵 - 홈카페 디저트 박스",
        business_type="디저트 박스샵",
        platform="인스타그램 피드",
        product_name="홈카페 디저트 박스",
        campaign_purpose="seasonal_event",
        tone="premium",
        template_hint="minimal_premium",
        price_text="구성 22,000원",
        user_constraints="홈파티 수요, 선물 패키지, 프리미엄 구성감",
    ),
)
